<?php

    $title = "Marmitas dona Dulce";

    $produtos = array(
        0 => array('id'=>'1', 'titulo'=>'Carne assada com legumes', 'descricao'=>'Quando pensamos em carne vermelha magra para ir ao forno, um dos com melhores no que se refere ao "custo-benefício" é o lagarto. Este é um dos cortes de carne com menor quantidade de gordura que podemos encontrar. Isso o torna um alimento saudável, desde que seja cozido da forma correta e, também, depende da guarnição: se o lagarto for à milanesa e frito, acompanhado de batatas e ovos fritos, não será tão saudável. Mas não se preocupe: nesta receita vamos ensinar a fazer uma carne simples, mas deliciosa e suculenta com uma variedade de legumes.','imagem'=>'imagens/img2.jpg'),
        1 => array('id'=>'2', 'titulo'=>'Carne assada com ricota', 'descricao'=>'Para pessoas demetarianas, que não deixam de consumir carne, mas evitam o exagero, essa carne assada é a melhor opção para manter a iguaria no cardápio. Fonte de proteínas, ela, consumida na medida certa, é muito importante para o nosso corpo, por ser um alimento que não tem substituto e contém vitaminas que não são encontradas em nenhum outro. Dentre outros nutrientes em destaque na carne, ela é rica em ferro, cálcio e vitaminas do complexo B, principalmente a vitamina B12. Além disso, a carne bovina é rica em cobre, potássio e magnésio, que deixam os músculos mais fortes e geram mais disposição ao organismo. Além disso, a receita conta com a pasta de ricota com alho, que dá um toque especial para a carne assada, diferenciando essa receita das outras. O tomate, de preferência orgânico, por sua vez, é um dos melhores acompanhamentos, dando leveza ao prato. Já o manjericão dá o aroma perfeito para essa mistura.','imagem'=>'imagens/img4.jpg'),
        2 => array('id'=>'3', 'titulo'=>'Frango frito', 'descricao'=>'Esse frango frito é para lá de picante graças ao pó da Bhut Jolokia, conhecida como pimenta-fantasma, a mais ardida do mundo, e uma generosa porção de pimenta-caiena. Não se engane, esta receita vai fazer seus olhos se encherem de lágrimas e sua língua estalar. Para apaziguar o ardor, sirva com fatias de um bom pão branco. Uma cerveja bem gelada também não fará mal. Para fazer, basta adicione 2 colheres (chá) de molho picante à salmoura de buttermilk. Antes de passar o frango na farinha, polvilhe-os com uma mistura de 3 colheres (chá) de pimenta-caiena, 1 colher (chá) de pimenta-fantasma em pó e 1 colher (sopa) de açúcar. Depois de fritar, polvilhe mais um pouco de caiena por cima. (Se você não achar Bhut Jolokia ou não quiser testar sua tolerância à pimentas tanto assim, use páprica defumada picante no lugar). ','imagem'=>'imagens/img6.jpg'),
        3 => array('id'=>'4', 'titulo'=>'Peito de frango com legumes', 'descricao'=>'Um prato com alta proteína, alta fibra, baixo carboidrato e cheio de nutrientes. Você pode substituir e ir adicionando diferentes tipos de proteína, como camarão, carne vermelha, peru, peixe ou até mesmo tofu. Você também pode adicionar todos os tipos de legumes e vegetais, deixando o prato a seu gosto e bem colorido. É tão versátil e gostoso que chega a ser viciante. Este frango com legumes refogado é definitivamente a receita perfeita para qualquer dieta!','imagem'=>'imagens/img8.jpg'),
        4 => array('id'=>'5', 'titulo'=>'Macarronada bolonhesa', 'descricao'=>'macarrão à Bolonhesa, que tem como origem, como o nome já diz, a região da Bolonha na Itália, é na verdade mais uma forma de utilizar um dos molhos mais conhecidos da culinária italiana, o molho à Bolonhesa. Este molho, a base de tomate e carne moída é usado em diversas outras receitas de massas, como por exemplo, a lasanha à Bolonhesa. Muita gente acha que uma receita de macarrão é simplesmente juntar um espaguete a um monte de carne moída com molho de tomate e pronto. Ledo engano. Um macarrão à Bolonhesa, daqueles que a gente jamais se esquece, tem também os seus segredos, e nesta receita vamos mostrar o passo a passo para que você surpreenda à todos com uma das receitas de macarrão simplesmente deliciosa.','imagem'=>'imagens/img9.jpg'),
        5 => array('id'=>'6', 'titulo'=>'Macarronada alho e óleo', 'descricao'=>'Espaguete ao alho e óleo (spaghetti aglio e olio) é um prato típico da culinária napolitana, parte do conjunto das chamadas cucina piccina partenopea (pequena cozinha napolitana). O prato é feito refogando levemente alho fatiado, picado ou prensado em azeite (soffritto), às vezes com a adição de finas fatias de pimenta fresca ou flocos de pimenta seca – nesse caso, seu nome é spaghetti aglio, olio e peperoncino. O espaguete ao alho e óleo não é tradicionalmente servido com queijo.','imagem'=>'imagens/img10.jpg'),
        6 => array('id'=>'7', 'titulo'=>'Refeição vegana', 'descricao'=>'Você já é adepto ou quer aderir ao veganismo? Além disso, tem muitas duvidas sobre o que comer e como montar pratos? Então, vou te ensinar como fazer comida vegana saborosa e simples. Diferente do que a maioria das pessoas imagina, o cardápio vegano, além de ser muito nutritivo, pode ser muito apetitoso e não se limita apenas a saladas e soja. Porém, na tentativa de suprir todos os nutrientes de que o nosso organismo necessita em uma refeição só, muita gente se perde. Aliás, há também quem se apega a uma quantidade limitada de receitas, e as refeições caem em uma mesmice.','imagem'=>'imagens/img11.jpg'),
        7 => array('id'=>'8', 'titulo'=>'Refeição integral', 'descricao'=>'O aproveitamento integral dos alimentos significa economia, e possibilita também experimentar novas opções de receitas, ressaltando assim, outro fator importante: a variação do cardápio. "Isso porque um único alimento rende até cinco preparações diferentes, repleta de nutrientes e coloridas, quando utilizamos sua casca, folha, talos, semente e a própria polpa", destacou a profissional.','imagem'=>'imagens/img13.jpg'),
    );
    $titulo = "História da nossa empresa";
    
    $historia = "No ano de 2010, minha mãe me ofereceu uma das churrascarias para que eu comprasse. 
    Foi lá que comecei a entregar refeições em obras, oportunidade que surgiu quase que por acaso.
    
    Um cliente me perguntou se eu podia fornecer comida para a obra da empresa dele, que contava 
    com vinte funcionários. Comecei e deu certo. Três meses depois, já fornecia 80 refeições e então 
    percebi que o faturamento da cozinha era superior ao do restaurante.
    
    Resolvi encerrar a churrascaria e aluguei uma garagem para montar a estrutura da cozinha”, relembra.
    Primeiro, dei início às atividades na garagem alugada, depois instalei a Mamitas da Dona Dulce em um 
    galpão. Hoje, trabalhamos em uma cozinha industrial, fornecendo não so marmitas mas refeições exclusivas
    
    Hoje apesar de ainda pequenos contamos com 15 funcionarios e uma rede de entrega complexa em toda a 
    capital Rondoniense.";
   
       
?>